### ISSUE TITLE
SRI - CCSM : Create Smart Contract

### ISSUE THREAD

**Issue by biscuitdey** [ethereum-oasis-op/baseline#797]
## Overview

There is one smart contract per BPI used to store all anchor hashes across all workgroups that are active in it.
implement the smart contract with the needed functionalities (add workgroup, add CAH...)

## Reference
#751 - For further details

## Tasks

- [ ] Create a solidity contract 
- [ ] Read/Write workgroupId to list
- [ ] Read/Write CAH to list

**Comment by biscuitdey** [comment]
Completed.
