### ISSUE TITLE
SRI - CCSM : Connect BPI with CCSM contract

### ISSUE THREAD

**Issue by biscuitdey** [ethereum-oasis-op/baseline#803]
## Overview

Allow BPI to deploy and interact with the CCSM smart contract.

### Reference

#751

### Assumptions

- BPI Admin will deploy the CCSM contract

## Tasks

- [ ] Use hardhat to deploy CCSM contract
- [x] Connect with CCSM contract
- [x] Call functions to set and get Anchor Hash
- [ ] Extend the e2e test to deploy an instance of the contract on local hardhat node

**Comment by ognjenkurtic** [comment]
We have opened separate  issues for remaining tasks #805 #812 #814
